<?php

use Drupal\connect_i\Entity\ImprovedNode;

/**
 * Implements hook_entity_type_alter() to override the Node class.
 */
function connect_i_entity_type_alter(array &$entity_types) {
  if (isset($entity_types['node'])) {
    // Set our custom class as the class for the Node entity.
    $entity_types['node']->setClass(ImprovedNode::class);
  }
}

/**
 * Implements hook_help().
 */
function connect_i_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.connect_i':
      return [
        '#theme' => 'item_list',
        '#list_type' => 'ol',  // This line changes the list to an ordered list.
        '#items' => [
          t('The block is called <strong>NodeListingBlock</strong> and is located in the <strong>connect_i</strong> module. I\'m not sure I understood correctly about "grouped by type", so I grouped by content type in alphabetical order and used rowspan (also some lines of CSS code, but it\'s just to make the table look clearer (I know it shouldn\'t be done that way)).'),
          t('I created a <strong>"Contrib module"</strong> as an example, where I created the <strong>OriginalService</strong> to later decorate it. The decorated service (<strong>DecoratedService</strong>) is located in the <strong>connect_i</strong> module.'),
          t('This task is also implemented in the <strong>connect_i</strong> module (<strong>RouteSubscriber</strong> and <strong>CustomAccessCheck</strong>). I didn\'t add the user field via UI because it\'s too simple; I did it using <strong>hook_install()</strong>.'),
          t('For the entity, I created a new module named <strong>test_custom_entity</strong>. The view in table format is available at the address - <strong>/referenced-node</strong>.'),
          t('This task is also implemented in the <strong>connect_i</strong> module (<strong>ImprovedNode</strong> and <strong>hook_entity_type_alter()</strong>).'),
          t('For the multi-step form, I created a new module called <strong>article_multistep</strong>.'),
          t('I also created a new module for the last task - <strong>server_time</strong>.'),
        ],
      ];
  }
}



