<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter() to override the node form for Article.
 */
function article_multistep_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'node_article_form' || $form_id == 'node_article_edit_form') {
    $form = \Drupal::formBuilder()->getForm('Drupal\article_multistep\Form\ArticlePageMultistepForm');
  }
}
